In [1]:
import numpy as np
from Assignments.Third.Model import MyFFLM

In [2]:
with open("lotrFotr.txt","r",encoding='utf-8') as file:
    raw_txt = file.read()

stripped_txt_lotr = raw_txt.replace('\n', ' ').replace('\t', ' ').replace('\r', ' ')\
    .replace(';', '').replace(':', '').replace('  ', ' ').replace('.', '').replace(',', '').lower().split()

with open("mobydick.txt","r",encoding='utf-8') as file:
    raw_txt = file.read()

stripped_txt_mb = raw_txt.replace('\n', ' ').replace('\t', ' ').replace('\r', ' ')\
    .replace(';', '').replace(':', '').replace('  ', ' ').replace('.', '').replace(',', '').lower().split()

In [3]:
vocab = list(set(stripped_txt_lotr))
vocab.sort()
vocab_dict = {}
for i, word in enumerate(vocab):
    identity_vector = np.zeros(len(vocab))
    identity_vector[i] = 1
    vocab_dict[word] = identity_vector

In [4]:
# Need to split up bc of ram issues, batches is the answer I think
memory_depth = 3
dataX = np.zeros((len(stripped_txt_lotr[:1000]) - memory_depth, memory_depth, len(vocab_dict)))
dataY = np.zeros(len(stripped_txt_lotr[:1000]) - memory_depth, dtype='int32')
for i in range(len(stripped_txt_lotr[:1000]) - memory_depth):
    x = np.zeros((memory_depth, len(vocab_dict)))
    for j in range(memory_depth):
        x[j] = vocab_dict[stripped_txt_lotr[:1000][i+j]]
    dataX[i] = x
    dataY[i] = np.argmax(vocab_dict[stripped_txt_lotr[:1000][i+memory_depth]])

In [5]:
reversed_dict = {}
for key in vocab_dict:
    reversed_dict[np.argmax(vocab_dict[key])] = key
for x in dataX[0]:
    print(reversed_dict[np.argmax(x)])
    print(x)
print(reversed_dict[dataY[0]])
print(dataY[0])

three
[0. 0. 0. ... 0. 0. 0.]
rings
[0. 0. 0. ... 0. 0. 0.]
for
[0. 0. 0. ... 0. 0. 0.]
the
11106


In [ ]:
v_len = len(vocab)
model = MyFFLM(v_len, 128, memory_depth)
for _ in range(50):
    for i, (x, y) in enumerate(zip(dataX, dataY)):
        y_t = np.zeros(v_len)
        y_t[y] = 1
        y_pred = model.forward(x)
        model.backprop(y_t, y_pred)
        if i % 500 == 0:
            print(np.argmax(y_pred), y)


12103 11106
